export const projectsData = [
	{
		name: "Cabin User App",
		img: "/1/holiday-cabin-app-1.png",
		id: 1,
		desc: "This is the customer facing page of the cabin project which I made the management app for. It uses the same data base. Users can browse the cabins and read a bit about the history of this place. They can browse the cabins and once they made up their mind they can book a stay. Users need to be logged in to make a booking, they can log in using their google account. Once logged in they can select a timeframe for the booking using a calendar, which only displays available dates. Once booked, they can check their reservations in the profile page, also delete or update them. On a separate tab they can change their details such as ID card number and name.",
		tech: [
			"Next.js",
			"React",
			"Tailwind",
			"Context API",
			"Auth.js",
			"Supabase",
			"Vercel",
		],
		github: "https://github.com/BenceM/cabin-app",
		site: "https://holiday-cabin-app-bencems-projects.vercel.app/",
	},
	{
		name: "Cabin Management App",
		img: "/1/holiday-cabin-app-1.png",
		id: 2,
		desc: "This is an internal holiday resort management app designed exclusively for BOH employees and managers. Currently, it is intended solely for PC use, specifically at the reception desk or in the office.Users are required to log in, where they can access their profile to customize settings such as setting an avatar, changing their name, and updating their password. Once logged in, users can manage cabins, bookings, guests and settings, including creating new ones, editing details, and deleting them. Cabins and bookings are displayed in a table view, allowing users to manage individual entries. They can add guests, update guest information, and check guests in or out as needed.The landing page provides a summary of key metrics, including guests, bookings, stay durations, and cash flow. This information is presented both numerically and visually, using charts.Additionally, users can update hotel-wide settings, such as the breakfast price, the maximum number of guests per booking, and the maximum number of nights allowed per booking.The app also features a dark mode for enhanced usability. To check the live page drop an email for a new log in",
		tech: [
			"React",
			"Tailwind",
			"TanStack Query",
			"Context API",
			"Supabase",
			"Styled Components",
			"Recharts",
			"Vite",
		],
		//update
		github: "https://github.com/BenceM/cabin-app",
		site: "https://holiday-cabin-app-bencems-projects.vercel.app/",
	},
	{
		name: "2D Platformer Game",
		img: "/3/2d-game-2.png",
		id: 3,
		desc: "A 2D Platformer game created in plain ES7+, CSS, HTML using canvas. This was my first attempt at creating a game. It was a steep learning curve, but it turned out okay. Canvas has some limitations and if I were to create a game again I'd probably use an engine, so I wouldn't have to create everything again from 0. The camera size is different on different screens depending on resolution and pixel density, to fix this the whole camera system would need a rework and most of the game. This I'd defintiely do differently in another iteration.",
		tech: ["JavaScript", "CSS"],
		github: "https://github.com/BenceM/2d-platformer",
		site: "https://bencem.github.io/2d-platformer/",
	},
	{
		name: "Countries Website",
		img: "/1/holiday-cabin-app-1.png",
		id: 4,
		desc: "A small project that uses an API for data fetching and display. This is an older project and my understanding of data fetching and handling greatly improved since then, would make the entire app much simpler, but regardless of code complexity, it runs decently well and it's pretty fast. Core functionality, displays all countries and flags. Can search for specific countries or filter based on location. Also has a separate page for each country where it shows more details. First time using the Intersection Observer.",
		tech: ["JavaScript", "CSS"],
		//update
		github: "https://github.com/BenceM/REST-countries",
		site: "https://bence-restcountriesapi.netlify.app",
	},
	{
		name: "Ai Image Generator",
		img: "/1/holiday-cabin-app-1.png",
		id: 5,
		desc: "This Project was my very first Ai model training project. It was a steep jump for me in difficulty as my Python was a bit rusty and I haven't used Next.js before, on top of that I had to learn how diffusors and image generators work. I ran the training on Jupyter Notebooks renting a computer from google as my rig wasn't made for this kind of computation. Once the training was done I dowloaded the model and hosted it on Hugging Face. Their API model always clears the API endpoints so the first generation might take a long while if it wasn't in use for a bit. Overall cool project, today I'd do many things differently and would write a cleaner code for the front end.",
		tech: ["Next.js", "Tailwind", "Hugging Face", "Ai models"],
		//update
		extra: "https://huggingface.co/BenceM/ai-avatar",
		github: "https://github.com/BenceM/ai-avatar",
		site: "https://bencem-ai-avatar.vercel.app/",
	},
];

//SKILLS

export const skillsData = {
	nodes: [
		{ id: "JavaScript", group: "core", img: "/jslogo.png", bg: false },
		{ id: "React", group: "core", img: "/ReactLogo.png", bg: false },
		{ id: "Next.js", group: "core", img: "/next-js.png", bg: true },
		{ id: "CSS", group: "css", img: "/csslogo.png", bg: false },
		{ id: "Tailwind", group: "css", img: "/tailwindcsslogo.png", bg: false },
		{ id: "Sass", group: "css", img: "/sass.png", bg: false },
		{
			id: "Styled Components",
			group: "css",
			img: "/styled-components.png",
			bg: false,
		},
		{
			id: "Router",
			group: "utils",
			img: "/react-routerlogo.png",
			bg: true,
		},
		{ id: "Context API", group: "utils", img: "/ReactLogo.png", bg: false },
		{ id: "Redux", group: "utils", img: "/reduxlogo.png", bg: false },
		{
			id: "TanStack Query",
			group: "utils",
			img: "/tanstacklogo.png",
			bg: false,
		},
		{ id: "Auth.js", group: "utils", img: "/auth-logo.png", bg: false },
		{ id: "Vercel", group: "hosting", img: "/vercel-logo.png", bg: false },
		{ id: "Git", group: "version", img: "/git-logo.png", bg: false },
		{ id: "Vite", group: "utils", img: "/vite-logo.png", bg: false },
		{ id: "D3", group: "data", img: "/d3.png", bg: false },
		{ id: "Recharts", group: "data", img: "/recharts.png", bg: false },
		{ id: "Motion", group: "css", img: "/motion-logo.png", bg: false },
		{ id: "Supabase", group: "data", img: "/supabase.png", bg: false },
		{ id: "Hugging Face", group: "data", img: "/hf-logo.png", bg: false },
	],
	links: [
		{ source: "JavaScript", target: "React" },
		{ source: "React", target: "Next.js" },
		{ source: "CSS", target: "Tailwind" },
		{ source: "CSS", target: "Sass" },
		{ source: "CSS", target: "Styled Components" },
		{ source: "React", target: "Router" },
		{ source: "React", target: "Context API" },
		{ source: "React", target: "Redux" },
		{ source: "React", target: "TanStack Query" },
		{ source: "React", target: "Auth.js" },
		{ source: "React", target: "Vite" },
		{ source: "CSS", target: "Motion" },
		{ source: "CSS", target: "Recharts" },
		{ source: "CSS", target: "D3" },
		// { source: "data", target: "Supabase" },
	],
};
